name: Deploy Articles

concurrency:
  group: deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - "blog-entries/**"

  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Deploy
        run: yarn cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


