name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true

on:
  schedule:
    - cron:  '0 2 * * *' 

  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Yarn install
        run: yarn install

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  check-types:
    name: Check Types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Yarn install
        run: yarn install

      - name: Execute Script
        run: yarn types

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Yarn install
        run: yarn install

      - name: Execute Script
        run: yarn lint


  deploy:
    name: Deploy
    needs: [check-types, lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Yarn install
        run: yarn install

      - name: Download App
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public

      - name: Deploy
        run: yarn cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

