name: Deployment Pipeline

concurrency:
  group: deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure node 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production
          GOOGLE_TRACKING_ID: ${{ secrets.GOOGLE_TRACKING_ID }}

      - uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  check-types:
    name: Check Types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure node 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Execute Script
        run: yarn types

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure node 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Execute Script
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure node 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Execute Script
        run: yarn test:ci

  deploy:
    name: Deploy
    needs: [check-types, lint, build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure node 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Download App
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public

      - name: Deploy Stack
        run: yarn cdk deploy --require-approval never --outputs-file outputs.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
