name: Nightly Redeploy
concurrency:
  group: deploy
  cancel-in-progress: true

on:
  schedule:
    - cron:  '0 2 * * *' 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  check-types:
    name: Check Types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Execute Script
        run: yarn types

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Execute Script
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Execute Script
        run: yarn test:ci


  deploy:
    name: Deploy
    needs: [check-types, lint, build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Yarn install
        run: yarn install --immutable

      - name: Download App
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public

      - name: Deploy Stack
        run: yarn cdk deploy --require-approval never --outputs-file outputs.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get S3 Bucket
        run: echo "UPLOAD_BUCKET=$(cat outputs.json | jq --raw-output 'keys[] as $k | .[$k] | .bucketoutput')" >> $GITHUB_ENV

      - name: Deploy Statics
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ env.UPLOAD_BUCKET }}
          source_dir: 'public'

      - name: Get Distribution ID
        run: echo "CLOUDFRONT_ID=$(cat outputs.json | jq --raw-output 'keys[] as $k | .[$k] | .apioutput')" >> $GITHUB_ENV

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ env.CLOUDFRONT_ID }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
